id: I5ACD68AE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:25:01+00:00'
last_modified: '2022-06-08T05:03:12.817148+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5673
  title: ཚད་མ་རིག་པའི་སྤྱི་དོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    9E16:
      image_group_id: I3CN5675
      title: ''
      total_pages: 604
      order: 1
      base_file: 9E16.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
