id: P005578
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN5673
  title: ཚད་མ་རིག་པའི་སྤྱི་དོན།
  author: ''
  volumes:
    9cce55bda4c843ac804046ce04546dc9:
      image_group_id: I3CN5675
      title: ''
      volume_number: 1
      total_pages: 604
      base_file: v001.txt
